### ISSUE TITLE
Multiple files upload from Google Photos application not working

### ISSUE THREAD

**Issue by rawbertp** [owncloud/android#1358]
Steps to reproduce:
1. Go to any folder in the ownCloud app
2. Click on Upload
3. Select "Content from other apps"
4. Select Google "Photos" app
5. Select multiple (e.g. 3) photos/files
6. Click "Done"

Actual outcome:
- Only one file is uploaded (instead of all 3)

Expected:
- All selected files get uploaded

**Comment by rishabh7m** [comment]
@AndyScherzinger Hi,  I am working on this if anyone has not started yet.

**Comment by AndyScherzinger** [comment]
Awesome! Go ahead, as far as I know no one else has started on this, looking forward to your fix :)

**Comment by malkomich** [comment]
Uploads from external apps are currently being fixed by @jabarros in PR https://github.com/owncloud/android/pull/1643.

So maybe, when it gets approved by QA, we should close this issue and PR https://github.com/owncloud/android/pull/1373 too, since many things has changed in uploads code for the last release.

**Comment by dpeger** [comment]
This actually still seems to be a thing. I this issue still WiP for more than 2 years?!

**Comment by davigonz** [comment]
Hi @dpeger , I've just tested this feature with ownCloud 2.6.0 in a Samsung Galaxy S7 Edge with Android 7 and is working fine, could you give it a try? If it works for you, I will close this since is already implemented

**Comment by dpeger** [comment]
@davigonz Oh, I kind of misread the issue, I thought it was about uploading images using the ownCloud web frontend, not the ownCloud app.

I'll delete my comment...

**Comment by davigonz** [comment]
No problem @dpeger. @rawbertp , could you test it with 2.6.0 ownCloud app and tell us whether is still not working for you?

**Comment by davigonz** [comment]
Closing this... if it happens again, please reopen it or open a new issue
