### ISSUE TITLE
"Folder doesn't exist anymore" on OwnCloud account with a space

### ISSUE THREAD

**Issue by basdv98** [owncloud/android#2347]
### Actual behaviour
- When I'm logged in to an OwnCloud account with a space in the username, I get the error in Dutch:
"Map /remote.php/dav/files/Folder name/Folder name/ bestaat niet meer". Translated: "Folder /remote.php/dav/files/Folder name/Folder name/ doesn't exist anymore".

We already tried to create a new account without a space, in that case it works. If we create another new account also with a space in it, it also doesn't work.

This doesn't work since 2 days so I expect the issue came with the 2.9.0 update.

It works just fine on the iOS app.

### Expected behaviour
- I should be able to browse files normally.
 
### Steps to reproduce
1. Create an account with a space in the username, for example "User name".
2. Log in to this account on the OwnCloud Android app.
3. It should now display the error at the bottom of the page.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
- No, I can't create an extra user on this server.

### Environment data
Android version: 7.0

Device model: Samsung Galaxy J5

Stock or customized system: Stock

ownCloud app version: 2.9.1

ownCloud server version: 10.0.10

#### Web server error log
- No lines are appearing when the error occurs.

#### ownCloud log (data/owncloud.log)
- No lines are appearing when the error occurs.

**Comment by jesmrec** [comment]
hi @basdv98. Could you upgrade to 2.9.1 and let us know if the problem is fixed?

**Comment by michaelstingl** [comment]
> Can this problem be reproduced with the official owncloud server?
> (url: https://demo.owncloud.org, user: test, password: test)
> 
> * No, I can't create an extra user on this server.

@basdv98 login with user: admin and pw: admin and create new user.

I created a new user `space user`, and opening a folder failed horrible with the error message described above.

I tested with a virtual Nexus 5 with Android 5.1.0 (API 22) in Genymotion.

**Comment by jesmrec** [comment]
Reproduced with Android 5 as well

**Comment by jesmrec** [comment]
@basdv98 we have pushed the 2.9.2 release, already available in Google Play. You can get it and give us your feedback about the reported problem.

**Comment by jasamples** [comment]
Also having this same issue with accounts that have a user name in an "email address" format like "test@gmail.com"

**Comment by davigonz** [comment]
> Also having this same issue with accounts that have a user name in an "email address" format like "test@gmail.com"

This is server related => https://github.com/owncloud/core/issues/33594

**Comment by davigonz** [comment]
> Also having this same issue with accounts that have a user name in an "email address" format like "test@gmail.com"

Thanks for reporting this @jasamples, this issue is about problems with spaces in the username, which has been already fixed in 2.9.2, so I will close it and please follow up https://github.com/owncloud/android/issues/2365

**Comment by davigonz** [comment]
Hi @jasamples , we've just released 2.9.3 to fix the problem you describe, please [download it via PlayStore](https://play.google.com/store/apps/details?id=com.owncloud.android), try it out and give us your feedback, thanks!

**Comment by jasamples** [comment]
Thanks @davigonz , we are back in business!  Everything is working well.

**Comment by BenjaminKobjolke** [comment]
The problem still exists with other special characters in Folder names.
I have folders like [--Work--] and for those folders the problem still persists.

**Comment by davigonz** [comment]
> The problem still exists with other special characters in Folder names.
I have folders like [--Work--] and for those folders the problem still persists.

@BenjaminKobjolke thanks for reporting your problem but this issue was about special characters in usernames and was already fixed, can you open a new issue with the details about what you have noticed?
