### ISSUE TITLE
Android app doesn't show available content on WebDAV share

### ISSUE THREAD

**Issue by j-ed** [owncloud/android#814]
## Expected behavior

If the ownCloud Android app is started it should connect to the ownCloud server and should show the available content of a user.
## Actual behavior

If the ownCloud Android app is started it connects to the ownCloud server but  the content of a user is not shown and the following messages are displayed:

```
Ladevorgang ...                       -> load process ...
Alles leer. Laden Sie etwas hoch!     -> All empty. Upload content!
```

The following messages can be found in the Apache2 log file, which indicated to me that a connection could be established:

```
"GET /owncloud/status.php HTTP/1.1" 200 77 "-" "Android-ownCloud" 576 2948
"PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 632 "-" "Android-ownCloud" 341 1546
```

The owncloud.log file shows hundreds of these messages:

```
{"reqId":"54972850dd112","app":"core","message":"DB execute with arguments : array (   0 => '13',   1 => '4fffea46331ab51134f008ce9b4671ef', )","level":0,"time":"2014-12-21 21:08:23+01:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"54972850dd112","app":"core","message":"DB execute with arguments : array (   0 => '13',   1 => 'd41d8cd98f00b204e9800998ecf8427e', )","level":0,"time":"2014-12-21 21:08:24+01:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"54972850dd112","app":"core","message":"DB execute with arguments : array (   0 => '13',   1 => 'ddbaf6bd108836d4afe269d86532a844', )","level":0,"time":"2014-12-21 21:08:24+01:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
```

If I access the WebDAV share from my desktop PC or if I use the web browser on my Android device to access it, the available content is instantly shown.
## Steps to reproduce

1.) Start the ownCloud Android app
2.) refresh the screen
3.) wait ...
#### Server Configuration

OS: Linux 3.2.54
Web server: Apache2 2.4.10 with **self-signed certificate**
Database: MySQL 5.1.73
PHP version: 5.4.35
ownCloud version: 7.0.4
#### Client Configuration

Operating system: Android 4.4.2
ownCloud Android app: v1.6.2
Wifi quality: excellent
Wifi speed: 65 Mbps

**Comment by j-ed** [comment]
Could anyone shed some light on how ownCloud differentiate between local and remote storage?
My assumption is that a kind of file check is done before the remote content is show to mobile clients which might cause heavy delays so that the clients are running into timeout.

**Comment by tobiasKaminsky** [comment]
@j-ed You are talking about the server part, right?

**Comment by j-ed** [comment]
@tobiasKaminsky Yes, my assumption is that the server API doesn't provide the requested information in a timely manner so that the whole connection times-out but this should be confirmed by someone who knows the underlying mechanism ;-)

**Comment by buzzra** [comment]
I am also having this problem. Webdav connections from Chrome for android, and via ES File explorer work fine. The Owncloud app says it connects to the server, no files are shown. If I do a 'refresh account' the app spins for a while and I get a "synchronization failed" notification in the notification bar. 

Interestingly, If I create a folder or file on the Android device, It updates just fine, even if I make changes or add files to the folder from the web client an my desktop.

My Owncloud home has a mixture of local files and folders, SMB share external storage, SFTP external storage, and cloud service external storage.

I am also running on a non-standard SSL port with a valid non-self signed cert.

buzz

**Comment by buzzra** [comment]
O.K., so today when I open the Android app, everything is there and the app works correctly. There have been no updates of the app or the server since my last post. Anyone have any idea what changed, or what the problem was?

**Comment by tobiasKaminsky** [comment]
No Idea.
But glad to hear that it works now.
Of course this is not satisfying as we could not figure out the reason for this...

If this happen again, please reopen.

**Comment by j-ed** [comment]
Unfortunately the problem still persists for me. What information do you need to get hold of the problem beside the already provided log information? Who else from the ownCloud team could shed some light on the used API?

**Comment by j-ed** [comment]
How could I re-open this issue? Unfortunately the Reopen button is not shown although it is shown for other closed issues?

**Comment by haeringer** [comment]
I have exactly the same problem:

- contents are shown as empty with android client, but creating folders and uploading files works
- refreshing leads to "synchronisation failed"
- showing contents with e.g. firefox webdav clients works fine
- problem first came up with v7, persists with v8.0
- nginx or apache don't make difference
- problem exists independently from android device (phone / tablet / v4 / v5 / ..), devices also work on demo.owncloud.org

Apache log messages:

    "GET /status.php HTTP/1.1" 200 1050 "-" "Android-ownCloud"
    "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1606 "-" "Android-ownCloud"

ownCloud log shows nothing. Any ideas on how to further investigate this issue?

**Comment by BerndSx** [comment]
I have exactly the same problem;-), but
the APP works on my Android tablett, while
login works on my phone but startpage shows "Alles leer. LadenSie etwas hoch"
"Empty. Please upload something" or whatever the message would be inn English.

**Comment by jowesten** [comment]
I have exactly the same problem. THe app works neither on my Samsung mobile nor on my Samsung tablet (I think both still have Android 4.2). It would be really great, if someone could help to overcome the problem (as BerndSx)

**Comment by a-schild** [comment]
I too have this issue. The immediate upload of images works, but the root content is not displayed.
Also no error on server side...
Server: Debian 8.0, 64Bit, Owncloud 8.0.3 Apache
Client: Sony XPeria 3Compact with Android 5.0.2 and App 1.7.1

**Comment by haeringer** [comment]
The issue is fixed for me since upgrading to 8.0.3. Could also have been 8.0.2 since I skipped that version, but:

* I did not make any changes besides the update 
* update was done manually by completely replacing the www/owncloud directory
* previous updates up to 8.0.0 - performed in the same way - did not solve the issue that was hunting me since 7.0.2 or .3 on all android devices

So I'm surprised (and sorry) to hear that you still got the issue with 8.0.3.

**Comment by jowesten** [comment]
I also had the problem that the content did not show, however, meanwhile this is fixed, but I don't know actually what exactly caused the error and what fixed it.
I have meanwhile installed 8.0.3 on the server, but I have the impression that the problem was on the client side, with the android app.
SInce I am using a Galaxy S4 mobile and and a Galaxy Note 10, both running under Android 4.2, I had the jelly bean work around installed which worked fine, until some time ago (I can't say exactly when the problem occured). Now I uninstalled the owncloud app and the jelly bean work around and reinstalled the app only, and wow: all of the sudden this configuration worked again.
May be, some others helps this procedure also.

**Comment by nudelz** [comment]
Hi,
I have the same problem. Can someone provide me some help?

OwnCloud 8.0.4
Android 4.4 (Custom Rom, rooted, Samsung Galaxy SIII)

What kind of information is additional needed ?

Thanks in advance.

**Comment by davivel** [comment]
@j-ed and all; this is probably another case of #940 that we overlooked. My apologies for that.

Version 1.7.2 of the app should fix it. We are in the process of testing it, should be available very soon.

I'll let this issue open just in case and ping you back when the version is released.

Thanks for your patience.

**Comment by a-schild** [comment]
Just upgraded to 1.7.2, but no change, still no content on the app. (Quota ~200GB and dropbox as external provider for one folder)
Server on 8.0.4, Debian 8.0.x, 64Bit

**Comment by Stonerocker** [comment]
problem persists on version 1.9.1 with latest stable owncloud server 8.2.2

**Comment by davivel** [comment]
Just to refresh my mind... the files do not appear if you pull down the list to enforce a refresh?

**Comment by Stonerocker** [comment]
Exactly. No files appear and synchronization fails. However, upload to the OwnCloud server works.

**Comment by davivel** [comment]
OK, I read slowly again, and I was losing important context. I'm sorry.

@Stonerocker , you have an external storage provider in your OC server enabled, right? Could you try to disable it temporary and see if the app works in that case?

**Comment by Stonerocker** [comment]
Sorry, no external storage provider. OC runs on a home base server on a qnap nas.

**Comment by DevWurm** [comment]
Same for me on Android App (Nexus 5, Android 6) and OwnCloud 9 Server. But the issue only appears on some remote folders, not all.

**Comment by DevWurm** [comment]
Accessing the folder in the WebApp works perfectly.

**Comment by Stonerocker** [comment]
The problem still remains in app vesion 2.0.0 on ownCloud server 8.2.5 without external storage support enabled. 

@davivel: Sorry, I missed your note about a probable connection to case #940. Indeed, I can  confirm that an account with around 1,000 files synchronizes well while other accounts with more than 20,000 files do not show any content. Hope this helps.

**Comment by davivel** [comment]
@Stonerocker , so, you don't have connected your OC to a Dropbox, Box or GDrive account? In that case, though the symptoms are similar, your problem is probably a different one. I would really appreciate if you opened a separate issue, including all the details of your comments. In the account with more than 20,000 files, how many files & folders do you have in the root folder?

@DevWurm , what do you mean with "remote folders"? Do you have any external storage provider enabled in your account?

**Comment by davivel** [comment]
Please, comment if needs to be reopened. Thanks.

**Comment by DevWurm** [comment]
The problem still exists. With remote folders I mean external WebDav storage .

**Comment by davivel** [comment]
Thanks, @DevWurm

**Comment by DevWurm** [comment]
Sorry for my late answer.

Some more details:
The error only occurs when accessing external storage folders.
The App shows all the subfolders, but when there are actual files in the folder, it shows the error "Nothing in here".

**Comment by davivel** [comment]
Thanks, @DevWurm . Could you tell me...
 - same problem with any external storage folder, or only some of them?
 - do you have files shared with you or shared with others in the faulty folders?
 - do you have encryption enabled in the server?
 - do you have the antivirus app enabled in the server?
 - which is the WebDAV provider you have mounted in those external folders?
 - what's your current OC server version?

Thanks in advance :)

**Comment by michaelstingl** [comment]
In version 2.9, the ownCloud Android app switched to a new networking library. I'd assume this issue is gone. In case this happens again, please open a new issue. (too many things changed)
